[default]
SQLALCHEMY_DATABASE_URI = 'sqlite:///test.db'
TITLE = "Python To You"
SECRET_KEY = "jadkfbsdkjbfbh"

BASE_URL = 'http://localhost:5000'

EXTENSIONS = [
    # Load all external dependencies for this project
    "python_to_you.extensions.database",
    "python_to_you.extensions.migrate",
    "python_to_you.extensions.marshmallow",

    # Load all internal dependencies for this project 
    "python_to_you.blueprints.routes.web",
    "python_to_you.blueprints.routes.api",
    "python_to_you.blueprints.routes.auth",
    "python_to_you.blueprints.components.header_menu",
    "python_to_you.blueprints.components.sidebar_left_menu",
    "python_to_you.blueprints.components.sidebar_right_menu",
    "python_to_you.blueprints.components.footer_menu"

]
SQLALCHEMY_TRACK_MODIFICATIONS = false

[development]
debug = true

[production]
debug = false
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql:///test.db'