[default]
SQLALCHEMY_DATABASE_URI = 'mysql:///test.db'
TITLE = "Python To You"
SECRET_KEY = "jadkfbsdkjbfbh"

EXTENSIONS = [
    "python_to_you.extensions.appearance"
]

[production]
SQLALCHEMY_DATABASE_URI = 'mysql:///test.db'